//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MaxMaterial.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_PARAMS                      4
#define IDS_SPIN                        5
#define IDS_TWOSIDES                    6
#define IDS_MTL1                        7
#define IDS_MTL1ON                      8
#define IDS_DONTCASTSHADOW              9
#define IDS_UNLIT                       10
#define IDS_NODEPTHCHECK                11
#define IDS_NODEPTHWRITE                12
#define IDS_CACHING                     13
#define IDS_ADDITIVELAYER               14
#define IDS_TEXTUREDCHANNEL             15
#define IDS_TEXTUREDCHANNEL_NONE        16
#define IDS_TEXTUREDCHANNEL_COLOR       17
#define IDS_TEXTUREDCHANNEL_TRANSPARENCY 18
#define IDS_TEXTUREDCHANNEL_INCADESCENCE 19
#define IDS_TEXTUREDCHANNEL_BUMPMAP     20
#define IDS_TEXTUREDCHANNEL_COMBINEDTEXTURES 21
#define IDS_TEXTURECHANGESTYLE          22
#define IDS_TEXTURECHANGESTYLE_SEQUENCE 23
#define IDS_TEXTURECHANGESTYLE_Random   24
#define IDS_TEXTURECHANGESTYLE_RANDOM   24
#define IDS_TEXTURECHANGESTYLE_Stop     25
#define IDS_TEXTURECHANGESTYLE_STOP     25
#define IDS_TEXTURERESOLUTION           26
#define IDS_TEXTURERESOLUTION_DEFAULT   27
#define IDS_TEXTURERESOLUTION_LOW       28
#define IDS_TEXTURERESOLUTION_MEDIUM    29
#define IDS_TEXTURERESOLUTION_HIGH      30
#define IDS_TEXTURERESOLUTION_HIGHEST   31
#define IDS_TEXTUREFILTER               32
#define IDS_TEXTUREFILTER_USEGLOBALSETTING 33
#define IDS_TEXTUREFILTER_NEAREST       34
#define IDS_TEXTUREFILTER_BILINEAR      35
#define IDS_TEXTUREFILTER_MIPMAP_NEAREST 36
#define IDS_TEXTUREFILTER_MIPMAP_LINEAR 37
#define IDS_TEXTUREFILTER_MIPMAP_BILINEAR 38
#define IDS_TEXTUREFILTER_MIPMAP_TRILINEAR 39
#define IDS_NODESTATE                   40
#define IDS_NODESTATE_NORMAL            41
#define IDS_NODESTATE_HASNOEFFECT       42
#define IDS_NODESTATE_BLOCKING          43
#define IDS_NODESTATE_WAITING_NORMAL    44
#define IDS_NODESTATE_WAITING_HASNOEFFECT 45
#define IDS_NODESTATE_WAITING_BLOCKING  46
#define IDS_COLOR                       47
#define IDS_UNNAMEDCOLOR                48
#define IDS_TCROTATESPEED               49
#define IDS_TEXTUREROWS                 50
#define IDS_TEXTURECOLS                 51
#define IDS_TEXTURECHANGEINTERVAL       52
#define IDS_TRANSLUSCENCECOEFF          53
#define IDS_DIFFUSEREFECTIVITY          54
#define IDS_INCANDESCENCE               55
#define IDS_MATERIAL                    56
#define IDS_UNNAMEDTRANSPARENCY         57
#define IDD_PANEL                       101
#define IDS_BLENDMODE                   101
#define IDS_BLENDMODE_OPAQUE            102
#define IDS_BLENDMODE_TRANSPARENT       103
#define IDS_BLENDMODE_ALPHABLEND        104
#define IDS_BLENDMODE_ADDITIVE          105
#define IDS_BLENDMODE_ADDITIVEALPHA     106
#define IDS_BLENDMODE_MODULATE          107
#define IDS_TCFLOWU                     108
#define IDS_TCFLOWV                     109
#define IDS_TCROTATE                    110
#define IDS_TCANGLERESET                111
#define IDS_TCPOSITIONRESET             112
#define IDS_TCFLOWSPEEDU                113
#define IDS_TCFLOWSPEEDV                114
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_CHECK1                      1001
#define IDC_COMBO1                      1002
#define IDC_CHECK2                      1003
#define IDC_CHECK3                      1004
#define IDC_CHECK4                      1005
#define IDC_CHECK5                      1006
#define IDC_CHECK6                      1007
#define IDC_DOSTUFF2                    1008
#define IDC_SLIDER1                     1009
#define IDC_SLIDER2                     1011
#define IDC_SLIDER3                     1013
#define IDC_SLIDER4                     1015
#define IDC_EDIT4                       1016
#define IDC_EDIT5                       1017
#define IDC_EDIT6                       1018
#define IDC_EDIT7                       1019
#define IDC_SLIDER5                     1020
#define IDC_EDIT8                       1021
#define IDC_SLIDER6                     1022
#define IDC_EDIT14                      1022
#define IDC_EDIT9                       1023
#define IDC_EDIT15                      1023
#define IDC_SLIDER7                     1024
#define IDC_EDIT16                      1024
#define IDC_EDIT10                      1025
#define IDC_EDIT17                      1025
#define IDC_SLIDER8                     1026
#define IDC_EDIT18                      1026
#define IDC_COMBO2                      1027
#define IDC_EDIT11                      1028
#define IDC_EDIT19                      1028
#define IDC_SLIDER9                     1029
#define IDC_CHECK7                      1030
#define IDC_CHECK8                      1031
#define IDC_CHECK9                      1032
#define IDC_CHECK10                     1033
#define IDC_COMBO3                      1034
#define IDC_COMBO4                      1035
#define IDC_COMBO5                      1036
#define IDC_CHECK11                     1037
#define IDC_COMBO6                      1038
#define IDC_CHECK12                     1039
#define IDC_EDIT12                      1040
#define IDC_EDIT13                      1041
#define IDC_SLIDER10                    1042
#define IDC_SLIDER11                    1043
#define IDC_SPIN1                       1044
#define IDC_SPIN2                       1045
#define IDC_SPIN3                       1046
#define IDC_CHECK13                     1047
#define IDC_SPIN4                       1048
#define IDC_SPIN5                       1049
#define IDC_SPIN6                       1050
#define IDC_SPIN7                       1051
#define IDC_SPIN8                       1052
#define IDC_SPIN9                       1053
#define IDC_CHECK14                     1054
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_SPIN                        1496
#define IDC_MTL1                        1497
#define IDC_MTLON1                      1498

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
