//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MaxParticle.rc
//
#define IDD_RAINPARAM                   169
#define IDC_ENABLE						1024
#define IDC_VISIBLE						1025
#define IDC_ATTACH_TO_EMITTER			1026
#define IDC_MOVE_WITH_EMITTER           1027
#define IDC_FOR_THE_SWORD               1028
#define IDC_FIXED_SIZE                  1029
#define IDC_HEAD                        1030
#define IDC_TAIL                        1031
#define IDC_UNSHADED                    1032
#define IDC_UNFOGGED                    1033
#define IDC_BLOCKBYY0                   1034
#define IDC_EMITTER_WIDTH               3044
#define IDC_EMITTER_WIDTHSPIN           3045
#define IDC_SWORD_INITIAL_NUM           3045
#define IDC_SWORD_INITIAL_ANGLE         3045
#define IDC_ASPECT_RATIOI               3046
#define IDC_EMITTER_HEIGHTSPIN          3047
#define IDC_INIT_ANGLE_BEGIN            3047
#define IDC_PARTICLE_SPEED              3048
#define IDC_PARTICLE_SPEEDSPIN          3049
#define IDC_PARTICLE_VARIATION          3050
#define IDC_SPEED_VARIATION             3050
#define IDC_PARTICLE_VARIATIONSPIN      3051
#define IDC_SPINNER_SPEED_VARIATIONSPIN 3051
#define IDC_PARTICLE_CUST               3052
#define IDC_CONE_ANGLE                  3052
#define IDC_TEXTEXAMPLE                 3053
#define IDC_PARTICLE_BIRTHRATE          3053
#define IDC_INIT_ANGLE_END              3053
#define IDC_PARTICLE_BIRTHRATESPIN      3054
#define IDC_ROTATION_SPEED              3054
#define IDC_PARTICLE_MAXRATE            3055
#define IDC_RATION_SPEED_VARIATION      3055
#define IDC_ROTATION_SPEED_VARIATION    3055
#define IDC_NO_CROSSOVER                3056
#define IDC_RND_PARTICLES               3056
#define IDC_EMITTER_LENGTH              3056
#define IDC_EMITTER_HEIGHT              3057
#define IDC_CONE_ANGLE_SPINNER          3058
#define IDC_GRAVITY                     3059
#define IDC_GRAVITY_SPINNER             3060
#define IDC_EXPLOSIVE_FORCE             3061
#define IDC_EXPLOSIVE_FORCE_SPINNER     3062
#define IDC_LIFE                        3063
#define IDC_LIFE_SPINNER                3064
#define IDC_LIFE_VARIATION              3065
#define IDC_LIFE_VARIATION_SPINNER      3066
#define IDC_EMISSION_RATE               3067
#define IDC_EMISSION_RATE_SPINNER       3068
#define IDC_INITIAL_NUM                 3069
#define IDC_INITIAL_NUM_SPINNER         3070
#define IDC_LIMIT_NUM                   3071
#define IDC_LIMIT_NUM_SPINNER           3072
#define IDC_TAIL_LENGTH                 3073
#define IDC_SPINNER_SWORD_INITIAL_ANGLE 3074
#define IDC_SPINNER_ASPECT_RATIO        3075
#define IDC_SPINNER_INIT_ANGLE_BEGIN    3076
#define IDC_SPINNER_INIT_ANGLE_END      3077
#define IDC_SPINNER_ROTATION_SPEED      3078
#define IDC_SPINNER_ROTATION_SPEED_VARIATION 3079
#define IDC_SPINNER_EMITTER_WIDTH       3080
#define IDC_SPINNER_EMITTER_LENGTH      3081
#define IDC_SPINNER_EMITTER_HEIGHT      3082
#define IDC_SPINNER_TAIL_LENGTH         3083
#define IDC_TIME_MIDDLE                 3084
#define IDC_SPINNER_TIME_MIDDLE         3085
#define IDC_ALPHA_R                     3092
#define IDC_SPINNER_ALPHA_R             3093
#define IDC_ALPHA_GREEN                 3094
#define IDC_SPINNER_ALPHA_G             3095
#define IDC_ALPHA_B                     3096
#define IDC_SPINNER_ALPHA_B             3097
#define IDC_SCALE_X                     3098
#define IDC_SPINNER_SCALE_X             3099
#define IDC_SCALE_Y                     3100
#define IDC_SPINNER_SCALE_Y             3101
#define IDC_SCALE_Z                     3102
#define IDC_SPINNER_SCALE_Z             3103
#define IDC_SCALE_VARIATION_X           3104
#define IDC_SPINNER_SCALE_VARIATION_X   3105
#define IDC_SCALE_VARIATION_Y           3106
#define IDC_SPINNER_SCALE_VARIATION_Y   3107
#define IDC_SCALE_VARIATION_Z           3108
#define IDC_SPINNER_SCALE_Z2            3109
#define IDC_SPINNER_SCALE_VARIATION_Z   3109
#define IDC_HEAD_LIFE_SPAN_X            3110
#define IDC_SPINNER_HEAD_LIFE_SPAN_X    3111
#define IDC_HEAD_LIFE_SPAN_Y            3112
#define IDC_SPINNER_HEAD_LIFE_SPAN_Y    3113
#define IDC_HEAD_LIFE_SPAN_Z            3114
#define IDC_SPINNER_HEAD_LIFE_SPAN_Z    3115
#define IDC_HEAD_DECAY_X                3116
#define IDC_SPINNER_HEAD_DECAY_X        3117
#define IDC_HEAD_DECAY_Y                3118
#define IDC_SPINNER_HEAD_DECAY_Y        3119
#define IDC_HEAD_DECAY_Z                3120
#define IDC_SPINNER_HEAD_DECAY_Z        3121
#define IDC_TAIL_LIFE_SPAN_X            3122
#define IDC_SPINNER_TAIL_LIFE_SPAN_X    3123
#define IDC_TAIL_LIFE_SPAN_Y            3124
#define IDC_SPINNER_TAIL_LIFE_SPAN_Y    3125
#define IDC_TAIL_LIFE_SPAN_Z            3126
#define IDC_SPINNER_TAIL_LIFE_SPAN_Z    3127
#define IDC_TAIL_DECAY_X                3128
#define IDC_SPINNER_TAIL_DECAY_X        3129
#define IDC_TAIL_DECAY_Y                3130
#define IDC_SPINNER_TAIL_DECAY_Y        3131
#define IDC_TAIL_DECAY_Z                3132
#define IDC_SPINNER_TAIL_DECAY_Z        3133
#define IDC_ATT_NONE                    4020
#define IDC_ATT_INV                     4021
#define IDC_ATT_INVSQ                   4022
#define IDC_LIGHT_TYPE2                 4042
#define IDC_CUSTOM1                     4139
#define IDC_CUSTOM2                     4141
#define IDC_CUSTOM3                     4142
#define IDC_COLOR_START                 4143
#define IDC_COLOR_MIDDLE                4144
#define IDC_COLOR_END                   4145
#define IDC_STATIC                      -1
#define IDC_HEAD2						4080
#define IDC_ROTATION_SPEED2				4081
#define IDC_ROTATION_SPEED3				4082
#define IDC_SPINNER_ROTATION_SPEED2		4083
#define IDC_SPINNER_ROTATION_SPEED3		4084

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         4144
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
